# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Phome_Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Phome_Project

  # target 'Phome_Project-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  # target 'Phome_ProjectTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

